### ISSUE TITLE
Bug: Sunken Shrine Power Seal location mixup

### ISSUE THREAD

**Issue by subenji** [alwaysintreble/TheMessengerTrackPack#1]
### What happened?

`Sunken Shrine Seal - Waterfall Paradise` and `Sunken Shrine Seal - Tabi Gauntlet` get marked as checked in place of each other. In AP, Tabi Gauntlet is marked as the seal on the lower left path and Waterfall Paradise as the one on the lower right path.

### What were the expected results?

Correct marking of items in the locations they are acquired.

### Is this reproducible?

Easily, just collect the items in question with the tracker active.

**Comment by alwaysintreble** [comment]
Oops. Fixed. Thanks!
