### ISSUE TITLE
Bug: 1.4.7's manifest still lists version as 1.4.6

### ISSUE THREAD

**Issue by powerlord** [alwaysintreble/TheMessengerTrackPack#2]
### What happened?

Downloaded the latest pack and overwrote the old one's zip file.  However, it claimed it was out of date and wanted to install an update to 1.4.7, which fails.

Looks closer at the files and the manifest.json still has this in it:

      "package_version": "1.4.6",

### What were the expected results?

Package version should be 1.4.7

      "package_version": "1.4.7",

### Is this reproducible?

1. Download tracker and install in PopTracker's packs directory.
2. Open Poptracker and load The Messenger tracker if necessary.
3. Poptracker will prompt to update to 1.4.7 despite it already being installed.

**Comment by alwaysintreble** [comment]
Fixed. Thanks.
